# Generated by Django 4.0.6 on 2022-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='product_rating',
            field=models.CharField(choices=[('ZERO', '0'), ('ONE', '1'), ('TWO', '2'), ('THREE', '3'), ('FOUR', '4'), ('FIVE', '5')], default='ZERO', max_length=250),
        ),
    ]
