# Generated by Django 4.0.6 on 2022-07-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userproducts_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='address',
        ),
        migrations.AddField(
            model_name='userproducts',
            name='decline_reason',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
