# Generated by Django 4.0.6 on 2022-07-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userdetail_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='address',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
