# Generated by Django 4.0.6 on 2022-07-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userdetail_about_me_userdetail_instagram_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
