# Generated by Django 4.0.6 on 2022-07-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userdetail_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
