# Generated by Django 4.0.6 on 2022-07-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userproducts_product_image_userproducts_user_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='userproduct',
        ),
        migrations.DeleteModel(
            name='UserProducts',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
