# Generated by Django 4.0.6 on 2022-08-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userdetail_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='order_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
