# Generated by Django 4.0.6 on 2022-08-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_userproducts_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='userproduct',
        ),
        migrations.DeleteModel(
            name='UserProducts',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
