# Generated by Django 4.0.6 on 2022-08-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_userrating_userproduct_delete_userproducts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('product_id', models.BigIntegerField()),
                ('order_id', models.CharField(max_length=250, unique=True)),
                ('product_name', models.CharField(max_length=250)),
                ('store_id', models.BigIntegerField()),
                ('price', models.IntegerField()),
                ('store_name', models.CharField(max_length=250)),
                ('product_image', models.CharField(blank='true', default='', max_length=250)),
                ('user_photo', models.FileField(blank=True, null=True, upload_to='product_images')),
                ('user_video', models.FileField(blank=True, null=True, upload_to='product_videos')),
                ('accept_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DECLINED', 'Declined')], default='PENDING', max_length=255)),
                ('product_description', models.CharField(default='', max_length=250)),
                ('product_rating', models.CharField(choices=[('ZERO', '0'), ('ONE', '1'), ('TWO', '2'), ('THREE', '3'), ('FOUR', '4'), ('FIVE', '5')], default='ZERO', max_length=250)),
                ('decline_reason', models.CharField(default='None', max_length=250)),
                ('quality_one', models.IntegerField()),
                ('quality_two', models.IntegerField()),
                ('customer_service', models.CharField(max_length=30)),
                ('customer_service_answer', models.IntegerField()),
                ('order_one', models.IntegerField()),
                ('order_two', models.IntegerField()),
                ('install_setup', models.IntegerField()),
                ('receive_product', models.CharField(max_length=30)),
                ('arrival_time', models.IntegerField()),
                ('damage_rating', models.IntegerField()),
                ('maintenance', models.FloatField()),
                ('feedback', models.CharField(max_length=30)),
                ('feedback_value', models.CharField(max_length=250)),
            ],
        ),
    ]
