# Generated by Django 4.0.6 on 2022-08-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_userproducts_customer_service_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='order_again',
            field=models.CharField(default='yes', max_length=30),
        ),
    ]
