# Generated by Django 4.0.6 on 2022-08-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_userproducts_order_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='arrival_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='customer_service_answer',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='damage_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='install_setup',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='maintenance',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='order_one',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='order_two',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='quality_one',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='quality_two',
            field=models.IntegerField(default=1),
        ),
    ]
