# Generated by Django 4.0.6 on 2022-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_userproducts_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='arrival_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='customer_service_answer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='damage_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='install_setup',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='maintenance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='order_again',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='order_one',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='order_two',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='quality_one',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='quality_two',
            field=models.IntegerField(),
        ),
    ]
